apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: jsiqbal/client
          context: client
          sync:
              manual:
                  - src: src/**/*.js
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jsiqbal/comments
          context: comments
          sync:
              manual:
                  - src: "*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jsiqbal/event-bus
          context: event-bus
          sync:
              manual:
                  - src: "*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jsiqbal/moderation
          context: moderation
          sync:
              manual:
                  - src: "*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jsiqbal/posts
          context: posts
          sync:
              manual:
                  - src: "*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jsiqbal/reaction
          context: reactions
          sync:
              manual:
                  - src: "*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: jsiqbal/query
          context: query
          sync:
              manual:
                  - src: "*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
